-- Create chat_support_config table
create table if not exists public.chat_support_config (
  id bigint generated by default as identity primary key,
  website_id text references public.websites(id) on delete cascade,
  is_enabled boolean default false,
  greeting_message text default 'Hi! How can we help you today?',
  agent_name text default 'Support',
  position text default 'bottom-right',
  chatbot_provider text default 'gemini',
  chatbot_api_key text,
  chatbot_bot_id text,
  chatbot_webhook_url text,
  chatbot_config jsonb default '{}'::jsonb,
  knowledge_base text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(website_id)
);

-- Enable RLS
alter table public.chat_support_config enable row level security;

-- Policies
-- Public read access (for the chat widget on the website)
create policy "Public can read chat config" on public.chat_support_config
  for select using (true);

-- Owners and editors can update
create policy "Owners and editors can update chat config" on public.chat_support_config
  for update using (
    exists (
      select 1 from public.websites
      where websites.id = chat_support_config.website_id
      and (
        websites.owner = auth.uid()
        or (websites.assignededitors is not null and websites.assignededitors @> jsonb_build_array(auth.jwt() ->> 'email'))
      )
    )
  );

-- Owners and editors can insert
create policy "Owners and editors can insert chat config" on public.chat_support_config
  for insert with check (
    exists (
      select 1 from public.websites
      where websites.id = chat_support_config.website_id
      and (
        websites.owner = auth.uid()
        or (websites.assignededitors is not null and websites.assignededitors @> jsonb_build_array(auth.jwt() ->> 'email'))
      )
    )
  );
